# Generated by Django 3.0.8 on 2020-07-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontype',
            name='sub_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='sub_duration',
            field=models.CharField(blank=True, choices=[('D', 'Day'), ('W', 'Week'), ('M', 'Month'), ('Y', 'Year')], default='W', max_length=200, null=True),
        ),
    ]
