# Generated by Django 3.0.8 on 2020-07-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200723_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontype',
            name='sub_desc',
            field=models.TextField(blank=True, default='testing', max_length=200),
        ),
    ]
