# Generated by Django 3.0.8 on 2020-07-23 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200723_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptiontype',
            name='sub_desc',
        ),
    ]
