# Generated by Django 3.0.8 on 2020-07-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_subscriptiontype_sub_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
