# Generated by Django 3.0.8 on 2020-07-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_subscriptiontype_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscriptions',
            name='sub_status',
        ),
        migrations.AddField(
            model_name='usersubscriptions',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
