# Generated by Django 3.0.8 on 2020-07-26 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200724_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptiontype',
            name='group',
        ),
        migrations.RemoveField(
            model_name='subscriptiontype',
            name='sub_unit',
        ),
        migrations.AddField(
            model_name='usersubscriptions',
            name='after_update_duration',
            field=models.CharField(blank=True, choices=[('D', 'Day'), ('W', 'Week'), ('M', 'Month'), ('Y', 'Year')], default='W', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usersubscriptions',
            name='after_update_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SubscriptionPrice'),
        ),
    ]
