# Generated by Django 3.0.8 on 2020-07-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200726_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontype',
            name='sub_duration',
            field=models.CharField(blank=True, choices=[('D', 'Day'), ('W', 'Week'), ('M', 'Month'), ('Y', 'Year')], default='M', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscriptions',
            name='after_update_duration',
            field=models.CharField(blank=True, choices=[('D', 'Day'), ('W', 'Week'), ('M', 'Month'), ('Y', 'Year')], default='M', max_length=200, null=True),
        ),
    ]
