# Generated by Django 3.0.8 on 2020-07-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200726_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, to='core.UserSubscriptions'),
        ),
        migrations.AlterField(
            model_name='usersubscriptions',
            name='after_update_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
