# Generated by Django 3.0.8 on 2020-07-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200726_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, to='core.UserSubscriptions'),
        ),
        migrations.AlterField(
            model_name='usersubscriptions',
            name='after_update_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
