# Generated by Django 3.0.8 on 2020-07-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200729_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='number_subscription_selected',
        ),
        migrations.AddField(
            model_name='usersubscriptions',
            name='number_subscription_made',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, to='core.UserSubscriptions'),
        ),
    ]
