# Generated by Django 3.0.8 on 2020-07-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200729_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, to='core.UserSubscriptions'),
        ),
        migrations.AlterField(
            model_name='usersubscriptions',
            name='number_subscription_made',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
