# Generated by Django 3.0.8 on 2020-07-29 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20200729_0158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='payment_status',
            new_name='is_paid',
        ),
        migrations.RenameField(
            model_name='usersubscriptions',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='invoice',
            name='payments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Payments'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, to='core.UserSubscriptions'),
        ),
    ]
