# Generated by Django 3.0.8 on 2020-07-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200729_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscriptions',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='usersubscriptions',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, to='core.UserSubscriptions'),
        ),
        migrations.AlterField(
            model_name='usersubscriptions',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
