# Generated by Django 3.0.8 on 2020-08-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20200814_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscriptions',
            name='expired',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, to='core.UserSubscriptions'),
        ),
    ]
